name: Docker CI

on:
  push:
    branches: [ "main" ]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t meena-app .

      - name: Run Docker container
        run: docker run -d -p 5000:5000 --name meena-container meena-app

      - name: Test app
        run: curl http://localhost:5000

